version: "3"

services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    restart: "unless-stopped"
    networks:
      default:
        aliases:
          - "paymentsandbox.test"

  payment_simulator:
    build: "docker/php"
    volumes:
      - ".:/var/www/html:rw"
    depends_on:
      - "nginx"
    restart: "unless-stopped"

networks:
  default:
